<?php
/**
 * Implements hook_form_alter().
 */
function set_weight_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['type'])) {
    $valid = FALSE;
    $select = dbselect('set_weight_setting');
    foreach ($select as $value) {
      $field_name = $value['field_name'];
      if (isset($form['type']['#value']) && $form['type']['#value'] == $value['type']) {
        if (isset($form[$field_name]['und'][0]['value']['#type']) && $form[$field_name]['und'][0]['value']['#type'] == 'textfield') {
          $valid = TRUE;
          $valueFname = $value['field_name'];
          $attr = array(
            'attributes' => array(
              'target'=>'_blank',
            ),
          );
          $original = $form[$field_name]['und'][0]['value']['#description'];
          $form[$field_name]['und'][0]['value']['#required'] = TRUE;
          $form[$field_name]['und'][0]['value']['#description'] = $original . ' ' . l('View ' . $form[$field_name]['und']['#title'] . ' values', "admin/sw-config/$valueFname/view" ,$attr);
        }
      }
    }
    if ($valid == TRUE) {
      $form['#validate'][] = 'validate_node_set_weight_values';
    }
	}
}


/**
 * Implements hook_menu().
 */
function set_weight_menu() {
  // A menu callback is required when using ajax outside of the Form API.
  $items['admin/config/system/sw-config'] = array(
  	'title' => 'Configure Set Weight',
  	'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('set_weight_admin_setting_form'),
    'file' => 'includes/set_weight.admin.inc',
  );
  
  $items['admin/sw-config/%/view'] = array(
    'title' => 'View Values',
    'weight' => 1,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('set_weight_view_form'),
    'access callback' => '_node_add_access',
    'file' => 'includes/set-weight-view.inc',
  );
  
  $items['admin/%/delete'] = array(
    'title' => 'Delete',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('set_weight_admin_settings_delete_form',1),
    'file' => 'includes/set_weight.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_node_insert().
 */
function set_weight_node_update($node) {
  update_set_weight_values($node);
}


/**
 * Implements hook_node_insert().
 */
function set_weight_node_insert($node) {
  insert_set_weight_values($node);
}


/**
 * Implements hook_node_delete().
 */
function set_weight_node_delete($node) {
  delete_set_weight_values($node);
}


/**
 * Implements hook_field_delete_field().
 */
function set_weight_field_delete_field($field) {
  if (isset($field['field_name'])) {
    $fieldname = $field['field_name'];
    $db = dbselectWhere('set_weight_setting',array('field_name'),'field_name',$fieldname);
    if (!empty($db)) {
      foreach ($db as $room) {
        dbdelete('set_weight_values', 'field_name',$room['field_name']);
        dbdelete('set_weight_setting', 'field_name',$fieldname);
      }
    }
  }
}


module_load_include('inc', 'set_weight', 'includes/helper');
module_load_include('inc', 'set_weight', 'includes/set_weight_form');